// <auto-generated />
namespace VectorShop.Migrations.VectorShopDb
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MainDbSchemaChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MainDbSchemaChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201509081408267_MainDbSchemaChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
