// <auto-generated />
namespace VectorShop.Migrations.IdentityDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class IdentitySchemaChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdentitySchemaChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201509081411011_IdentitySchemaChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
